apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
   metadata:
     labels:
       app: broker
   spec:
     containers:
      - name: broker
        image: censoree/mqtt-broker-ts:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 1883
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP